version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: always
    volumes:
      - .:/var/www
      # TIMPA .env container dengan .env.prod host agar 100% aman
      - ./.env.prod:/var/www/.env
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: nginx-server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      # Pastikan Anda punya file config nginx di folder ./nginx/conf.d/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: mysql:oraclelinux9
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: jobportal
      MYSQL_ROOT_PASSWORD: Hesoyam1!
    ports:
      - "3307:3306"
    volumes:
      # PENTING: Agar data tidak hilang saat container mati
      - db_data:/var/lib/mysql

volumes:
  db_data:
